name: myenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cpuonly
  - fastapi
  - uvicorn
  - requests
  - pillow
  - numpy
  - python-dotenv
  - pip
  - pip:
    - git+https://github.com/openai/CLIP.git